# slam_params.yaml
# Configuration for the slam_toolbox node for the Slambot.

slam_toolbox:
  ros__parameters:
    # PLUGIN PARAMETERS
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_preconditioner: "SCHUR_JACOBI"
    ceres_trust_strategy: "DOGLEG"
    ceres_dogleg_type: "TRADITIONAL_DOGLEG"
    ceres_loss_function: "None"

    # ROS-RELATED PARAMETERS
    odom_frame: "odom" #We aren't using prefixed frames here but if you were (e.g. myrobot_odom) then need to account for that here
    map_frame: "map" #We aren't using prefixed frames here but if you were (e.g. myrobot_map) then need to account for that here
    base_frame: "base_footprint" #Make sure to use 'base_footprint' (not 'base_link') if you have a base_footprint to ensure a complete TF tree
    scan_topic: "scan" #We ARE using namespaced topics (e.g. myrobot/scan) but don't worry the launch file will handle dynamic topic namespacing

    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1 # <-- DECREASED: Process scans more frequently to reduce drift between updates.
    minimum_travel_heading: 0.17
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.15
    link_scan_maximum_distance: 1.0 # <-- DECREASED: Creates a denser pose graph for better tracking.
    do_loop_closing: true
    loop_search_maximum_distance: 10.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.55
    loop_match_minimum_response_fine: 0.65

    # CORRELATION PARAMETERS
    correlation_search_space_dimension: 0.8
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # SCAN MATCHER PARAMETERS
    distance_variance_penalty: 0.2
    angle_variance_penalty: 0.4 # <-- DECREASED: Trust odometry rotation less, rely more on scan matching.
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # GENERAL PARAMETERS
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.25
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Ceres Scan Matcher options
    ceres_scan_matcher:
      use_nonmonotonic_steps: false
      max_num_iterations: 20
      ceres_solver_options:
        use_explicit_schur_complement: true
        max_num_iterations: 10
        num_threads: 4
        num_linear_solver_threads: 4
